# Site settings
title: Super Quick Notes
email: dfrancesconi12@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Minimal jotted down notes.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://danfran.github.io" # the base hostname & protocol for your site
github_username: danfran
theme: minima
# Build settings
markdown: kramdown
google_analytics: UA-88031393-1
